@startuml Автоспот: логическая модель данных заказа

left to right direction

class "Заявка" as Application {
    Идентификатор заявки
    Тип заявки
    Возможные способы покупки []
    Клиент
}

enum "Способ покупки" as PaymentType {
    Идентификатор способа покупки
    Название способа покупки\n(Кредит, трейд-ин и т.д.)
}

class "Клиент" as Customer {
    Идентификатор клиента
    Имя
    Фамилия
    Отчество
    Город
    Номер телефона []
}

class "Заказ" as Order {
    Идентификатор заказа
    Идентификатор заявки
    Марка авто
    Модель авто
    Клиент
    Дилер []
    Способ оплаты  
}

class "Дилер" as Dealer {
    Идентификатор дилера
    Название компании
    Адрес
}

Application "n" -- "1  " Customer
Application "n" -- "m" PaymentType
PaymentType  "1" -- "1" Order
Customer "n" -- "1" Order 
Order "1" -- "n" Dealer


@enduml