openapi: 3.0.3
info:
  title: Swagger Autospot - OpenAPI 3.0
  description: Endpoint for Autospot test task

  version: 0.1.0

servers:
  - url: https://grizzlyorange.ucoz.net
tags:
  - name: OrdersAtAdminPanel
    description: Manage orders at admin panel 

paths:
  /v1/admin/orders/dealers.json:
    get:
      tags:
        - OrdersAtAdminPanel
      summary: Get dealers list by params
      description: Get dealers list by params
      operationId: getDealersByParams
      
      parameters:
        - in: query
          name: brandId
          schema:
            type: integer
          required: true
          description: car brand id
        - in: query
          name: modelId
          schema:
            type: integer
          required: true
          description: car model id

        - in: query
          name: cityId
          schema:
            type: integer
          required: true
          description: search city id
        
        - in: query
          name: carStateId
          schema:
            type: integer
          required: true
          description: car state id

        - in: query
          name: limit
          schema:
            type: integer
          required: false
          description: results count on page

        - in: query
          name: offset
          schema:
            type: integer
          required: false
          description: results offset (in results items)

        
      
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DealersResponse'
        '400':
          description: Invalid params
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParamsResponse'
        '401':
          description: User is not authorized
        '403':
          description: User has no access to action
        '500':
          description: Internal server error

  
components:
  schemas:

    DealersResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            meta:
              type: object
              properties:
                limit:
                  type: integer
                  description: Количество результатов в запросе
                  example: 20
                offset:
                  type: integer
                  description: Сколько результатов пропущено до первого в выдаче
                  example: 0
            dealers:
              type: array
              items:
                $ref: '#/components/schemas/DealerAndCarPrice'
          required:
            - dealers
            - meta
      required:
        - data
        
    DealerAndCarPrice:
      type: object
      properties: 
        dealer: 
          type: object
          properties:
            dealerBranchId:
              type: integer
              description: Идентификатор отделения дилера
              example: 1520
            dealerBranchName:
              type: string
              description: Название отделения дилера
              example: "Рольф Краснодар Audi"
            dealerBranchAddress:
              type: string
              description: Адрес отделения дилера
              example: "Краснодар, ул. Уральская, д. 98/11"
          required:
            - dealerBranchId
            - dealerBranchName
            - dealerBranchAddress
        carPrice: 
          type: object
          properties:
            sum:
              type: integer
              description: Стоимость
              example: 8796000
            currencyId:
              type: string
              description: Идентификатор валюты
              example: rub
            priceDisplay:
              type: string
              description: Стоимость с валютой, согласно настройкам админки
              example: 8.796.000 рублей
          required:
            - priceDisplay
            - sum
            - currencyId
      required:
        - dealer
        - carPrice

    InvalidParamsResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            messageForUser:
              type: string
              description: Сообщение для пользователя
              example: Неверно указаны параметры. Измените значения и попробуйте снова.
            errors:
              type: array
              items:
                $ref: '#/components/schemas/InvalidParamsError'
          required:
            - messageForUser
            - errors
      required:
        - data

    InvalidParamsError:
      type: object
      properties: 
        param:
          type: string
          description: Параметр
          example: cityId
        errorId:
          type: string
          description: Идентификатор ошибки
          example: not_found
        errorMessage:
          type: string
          description: Текст ошибки
          example: Город не найден
      required:
        - param
        - errorId
        - errorMessage