@startuml Автоспот: физическая модель данных заказа

left to right direction

class Application {
    PK applicationId: Int
    FK applicationTypeId: Int
    customerPhone: String
    customerName: String
}

enum ApplicationType {
    PK applicationTypeId: Int
    applicationTypeName: String
}

enum PaymentType {
    PK paymentTypeId: Int
    paymentTypeName: String
}

class ApplicationPaymentType {
    FK applicationId: Int
    FK paymentTypeId: Int
}

class Customer {
    PK customerId: Int
    name: String
    middleName: String
    lastName: String
    FK cityId: String
}

class CustomerPhones {
    FK customerId: Int
    phone: String
    isActive: Boolean
    isDefault: Boolean
}

enum City {
    PK cityId: Int
    cityName: String
}

class Order {
    PK orderId: Int
    FK carStateId: Int
    FK modelId: Int
    FK customerId: Int
    FK paymentType: Int
    FK orderStateId: Int
    createdAt: DateTime
    updatedAt: DateTime
}

enum OrderState {
    PK orderStateId: Int
    orderStateName: String
}

enum CarState {
    PK carStateId: Int
    carStateName: String
}

class CarBrand {
    PK carBrandId: Int
    carBrandName: String
}

class CarModel {
    PK carModelId: Int
    FK brandId: Int
    carModelName: String
}

class OrderDealers {
    FK orderId: Int
    FK dealerBranchId: Int
}

class DealerCompany {
    PK dealerCompanyId: Int
    companyName: String
}

class DealerBranch {
    PK dealerBranchId: Int
    FK dealerCompanyId: Int
    dealerBranchName: String
    FK cityId: Int
    street: String
    houseNumber: String
}

Application "n" -- "1" ApplicationType
Application "1" -- "n  " ApplicationPaymentType
ApplicationPaymentType "n" -up- "1    " PaymentType
Order "n" -- "1" PaymentType
Order "n" -- "1" CarState
Order "n" -- "1  " CarModel
CarModel "n" -left- "1  " CarBrand  
Customer "1" -- "n" CustomerPhones
Customer "n" -- "1  " City
Customer "1" -right- "n" Order
Order "1" -right- "n" OrderDealers
OrderDealers "n" -- "1" DealerBranch
DealerBranch "n" -- "1" DealerCompany
DealerBranch "n" -- "1  " City

Order "n" -- "1" OrderState

'Application "n" -- "1" ApplicationType
'Application "1" -- "n" ApplicationPaymentType
'ApplicationPaymentType "n" -- "1" PaymentType


@enduml